### PR TITLE
WIP: Alpine-ized base image

### PR DESCRIPTION
**Pull request by pieterlange**
Hey! Cool project.

Was just playing around with it a bit and tried to cut down on the (huge!) image size. Managed to get it down to 400MB.

```
$ docker images  | head
REPOSITORY                                          TAG                 IMAGE ID            CREATED             SIZE
cyphon-alpine                                       latest              4b65a6c55054        37 seconds ago      410MB
cyphon                                              latest              e789aa288d78        34 minutes ago      1.03GB
```

Yet untested.

### CODE REVIEW

**Comment by lhadjchikh** [comment]
I would LOVE to get the image size down, thank you! It looks like a few functional tests failed, but sometimes that happens randomly (I think it's because Travis-CI can't connect to SauceLabs). I'm going to close and then reopen this PR to trigger another build, and we'll see what happens! :-)

**Comment by lhadjchikh** [comment]
Oh wait, I think this is just an authentication issue. I'll have to create a new branch from your PR so Travis-CI can use our SauceLab credentials...

**Comment by pieterlange** [comment]
Not sure what you changed, but https://travis-ci.org/dunbarcyber/cyphon/builds/235022003 was successful :+1:

**Comment by lhadjchikh** [comment]
Actually I didn't change anything! It just needed access to the environmental variables for authenticating with SauceLabs and Twitter that we set up on Travis-CI. The settings are only associated with the dunbarcyber/cyphon repo, though, so a PR from another fork will fail on tests that need those credentials. I created a [new branch](https://github.com/dunbarcyber/cyphon/tree/pull-58) from your PR, which triggered another Travis build, and it transferred over the results. :-)

**Comment by pieterlange** [comment]
Ah, got it :)

**Comment by lhadjchikh** [comment]
Okay, I renamed the branch "alpine" and built a Docker image at dunbar/cyphon:alpine. We'll give it a try on our dev server tomorrow. Thanks!!

**Comment by lhadjchikh** [comment]
Whoops, after all that, I realized we have to test the image using Cyphondock! This repo only tests a regular install, so the tests here weren't actually telling us anything useful. Cyphondock handles the Docker-based tests. Sorry, I'd forgotten that! I obviously need a better workflow for testing the Cyphon image, as it's not very intuitive.

The good news is that Cyphondock uses a Selenium container for the functional tests, so at least we don't need to worry about connecting to SauceLabs.

I created a new pull request [here](https://github.com/dunbarcyber/cyphondock/pull/14). I'll revisit this in the morning. :-)

**Comment by lhadjchikh** [comment]
I took a shot at testing the new Alpine image. When starting the container, I got an error:
```
ImportError: cannot import name 'GDALRaster'
```
This appears to be fixed by changing the package on line 38 of the Dockerfile to `gdal-dev`.

After changing that line, I ran tests, which produced a different error:
```
ImportError: Could not find the GEOS library (tried "geos_c", "GEOS"). Try setting GEOS_LIBRARY_PATH in your settings.
```
This is another error related to the geospatial libraries required by GeoDjango ([see documentation](https://docs.djangoproject.com/en/1.11/ref/contrib/gis/install/geolibs/)). They've given me trouble in the past, as well...

**Comment by pieterlange** [comment]
I'll try to put some more effort into real-life testing this... just had something that built and wanted to contribute it before i forgot.

**Comment by lhadjchikh** [comment]
Awesome, thanks so much! I don't think it's too far off from working.

**Pull request closed without merging**
